baseURL = 'https://hugo.blog-theme.orb.local'
languageCode = 'en-us'
title = 'My New Hugo Site'

enableGitInfo = true

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [[ "\\[", "\\]" ], [ "\\(", "\\)" ], [ "$$", "$$" ]]
          inline = [[ "\\(", "\\)" ], [ "$", "$" ]]
  [markup.asciidocExt]
    extensions = [ "asciidoctor-diagram" ]
    # preserveTOC = true
    workingFolderCurrent = true
    # tocLevels = 4
    [markup.asciidocExt.attributes]
      idprefix = "id-"
      idseparator = "-"
      my-attribute-name = "my-attribute-value"
      my-base-url = "http://localhost:1313"
      source-highlighter = "rouge"

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  math = true

[security]
  [security.exec]
    allow = [ "^asciidoctor$", "^git$" ]